import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import {
    MatToolbarModule,
    MatGridListModule,
    MatInputModule,
    MatFormFieldModule,
    MatListModule,
    MatCardModule,
    MatButtonModule,
    MatProgressSpinnerModule,
    MatCheckboxModule,
    MatMenuModule,
    MatIconModule,
    MatSidenavModule,
    MatExpansionModule,
    MatTooltipModule,
    MatSnackBarModule,
    MatDialogModule,
    MatAutocompleteModule,
    MatSlideToggleModule,
    MatTabsModule,
    MatSelectModule,
    MatNativeDateModule,
    MatDatepickerModule } from '@angular/material';

@NgModule({
    imports: [
        MatToolbarModule,
        MatGridListModule,
        MatInputModule,
        MatFormFieldModule,
        MatListModule,
        MatCardModule,
        MatButtonModule,
        MatProgressSpinnerModule,
        MatCheckboxModule,
        MatMenuModule,
        MatIconModule,
        MatSidenavModule,
        MatExpansionModule,
        MatTooltipModule,
        MatSnackBarModule,
        MatDialogModule,
        MatAutocompleteModule,
        MatSlideToggleModule,
        MatTabsModule,
        MatSelectModule,
        MatNativeDateModule,
        MatDatepickerModule ],
    exports: [
        MatToolbarModule,
        MatGridListModule,
        MatInputModule,
        MatFormFieldModule,
        MatListModule,
        MatCardModule,
        MatButtonModule,
        MatProgressSpinnerModule,
        MatCheckboxModule,
        MatMenuModule,
        MatIconModule,
        MatSidenavModule,
        MatExpansionModule,
        MatTooltipModule,
        MatSnackBarModule,
        MatDialogModule,
        MatAutocompleteModule,
        MatSlideToggleModule,
        MatTabsModule,
        MatSelectModule,
        MatNativeDateModule,
        MatDatepickerModule]
})

export class MaterialModule { }
